export const ADD_ARTICLE = "ADD_ARTICLE";
export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const WS_CONNECT_TO_SERVER ="WS_CONNECT_TO_SERVER";
export const WS_CONNECTED_TO_SERVER ="WS_CONNECTED_TO_SERVER";
export const WS_OPEN_TEST_CANAL = "WS_OPEN_TEST_CANAL";
export const WS_SEND_TEST_MESSAGE = "WS_SEND_TEST_MESSAGE";