export const WS_CONNECT_TO_SERVER ="WS_CONNECT_TO_SERVER";
export const WS_CONNECTED_TO_SERVER ="WS_CONNECTED_TO_SERVER";
export const WS_OPEN_PRIVATE_CANALS = "WS_OPEN_PRIVATE_CANALS";
export const WS_SEND_MESSAGE = "WS_SEND_MESSAGE";
export const WS_GET_GAMES_LIST = "WS_GET_GAMES_LIST";
export const WS_GOT_GAMES_LIST = "WS_GOT_GAMES_LIST";

export const WS_CONNECT_TO_GAME = "WS_CONNECT_TO_GAME";
export const WS_GAME_CONNECTED = "WS_GAME_CONNECTED";

export const WS_CANNEL_CONNECT = "WS_CANNEL_CONNECT";
export const WS_CANNEL_DISCONNECT = "WS_CANNEL_DISCONNECT";
export const WS_CANNEL_SUBSCRIPTION = "WS_CANNEL_SUBSCRIPTION";

export const WS_GAME_CREATED = "WS_GAME_CREATED";
export const WS_GAME_UPDATED = "WS_GAME_UPDATED";



export const REGISTER = "REGISTER";
export const REGISTERED = "REGISTERED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const LOGIN = "LOGIN";
export const LOGGED = "LOGGED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const AUTH_FROM_COOKIES = "AUTH_FROM_COOKIES";

export const SET_COOKIES_SERVICE= "SET_COOKIES_SERVICE";
export const SET_HISTORY = "SET_HISTORY";