export const WS_CONNECT_TO_SERVER ="WS_CONNECT_TO_SERVER";
export const WS_CONNECTED_TO_SERVER ="WS_CONNECTED_TO_SERVER";
export const WS_OPEN_PRIVATE_CANALS = "WS_OPEN_PRIVATE_CANALS";
export const WS_SEND_MESSAGE = "WS_SEND_MESSAGE";
export const WS_GET_GAMES_LIST = "WS_GET_GAMES_LIST";
export const WS_GOT_GAMES_LIST = "WS_GOT_GAMES_LIST";

export const REGISTER = "REGISTER";
export const REGISTERED = "REGISTERED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const LOGIN = "LOGIN";
export const LOGGED = "LOGGED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const AUTH_FROM_COOKIES = "AUTH_FROM_COOKIES";

export const SET_COOKIES_SERVICE= "SET_COOKIES_SERVICE";